drop table IF EXISTS `CLIENT`;

create table `CLIENT`
(
  `id` VARCHAR(250) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `loggedIn` BIT DEFAULT 0
);

-- SET PRIMARY KEY
ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_CONS_1 PRIMARY KEY(id);
-- SETUP INDEXES  ------------------------
CREATE INDEX CLIENT_EMAIL_INDEX ON CLIENT(email);
CREATE INDEX CLIENT_NAME_INDEX ON CLIENT(name);